version: '3'
services:
  db:
    image: postgres:11-alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: db
    restart: always
    user: root
  pgadmin4:
    image: dpage/pgadmin4:3.3
    container_name: pgadmin4
    ports:
      - 80:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/strage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    restart: always
  fluentd:
    image: fluent/fluentd:v1.5-1
    container_name: fluentd
    ports:
     - "24224:24224"
#    environment:
#      FLUENTD_CONF: fluentd.conf
    volumes:
     - ./fluentd/conf/fluentd.conf /fluentd/etc/fluentd.conf
    ports:
     - "24224:24224"
     - "24224:24224/udp"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
