version: '3'

services:
  batch:
    build: ./
    env_file:
     - ./local.env
    command: /app/sample-batch -SqlFile /app/sql/BAT0000_update-to-diable-invalid-users.sql
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.1.2:24224 # set your host IP address.
        tag: docker.sample_batch
networks:
  default:
    external:
      name: daemons_default
   

